### ISSUE TITLE
BACnet server off the client how to know

### ISSUE THREAD

**Issue by chenzx1020** [ela-compil/BACnet#3]
Hi @gralin, I have a question to ask you, If the BACnet server is closed, through the BacnetClient object with propertys or events to know that the server has been closed?

**Comment by gralin** [comment]
@chenzx1020 since the communication is done thru connectionless protocol (UDP), there is no open connection that could be monitored (like with TCP). Your safest bet to know if server is available is periodically reading its DEVICE_OBJECT properties or sending WHO_IS command and listenning for I_AM response from your server.
