### ISSUE TITLE
BacnetObjectId contains ambiguous members type and instance

### ISSUE THREAD

**Issue by Padanian** [ela-compil/BACnet#63]
Type and Instance properties have ambiguous names with type and instance fields.
See image. In order to solve for the ambiguity, resorting to Reflection is required.

![Immagine 2020-12-01 152814](https://user-images.githubusercontent.com/7769348/100755791-d7c14c80-33ec-11eb-8fc5-b90119b1c3f1.png)
![Immagine 2020-12-01 152744](https://user-images.githubusercontent.com/7769348/100755795-d859e300-33ec-11eb-87f2-cf8204104266.png)

**Comment by gralin** [comment]
Hi @Padanian, you are right, this code was written in C# and this error is VB specific (names are case-insensitive). I didn't remove or rename the type/instance fields when introducing the properties, becuase the fields were made public by previous contributors and I didn't want to introduce breaking changes. Of course the corresponding properties could have been named differently but I didn't think about VB use case. I'm afraid nothing we can do about it now, and this would have to be fixed in complete codebase rewrite where breaking changes could be introduced. If this code was written by me from the beginning, the fields would not be public nor would they be named the same as properties, but it is how it is... Sorry for that.
